import { colors } from './colors'
import { fonts } from './fonts'

export function generateV4Theme(paletteName: 'storefront' | 'admin' | 'dark' = 'storefront'): string {
  const p = colors[paletteName]
  return `/* Auto-generated by @ai-whisperers/theme — edit colors.ts, not this file */
@theme {
  --color-primary: ${p.primary};
  --color-primary-foreground: ${p.primaryForeground};
  --color-secondary: ${p.secondary || '#4B5563'};
  --color-accent: ${p.accent || '#F59E0B'};
  --color-background: ${p.background};
  --color-foreground: ${p.foreground};
  --color-muted: ${p.muted};
  --color-muted-foreground: ${p.mutedForeground};
  --color-border: ${p.border};
  --color-card: ${p.card};
  --color-card-foreground: ${p.foreground};
  --color-ring: ${p.ring};
  --color-destructive: ${p.destructive || '#EF4444'};
  --color-success: ${p.success || '#22C55E'};
  --color-warning: ${p.warning || '#F59E0B'};
  --font-sans: ${fonts.sans};
  --font-heading: ${fonts.heading};
}`
}
